In [ ]:
from CHDS import CHDS_synthesizer
import pandas as pd
import kagglehub
import os

In [ ]:
# Example usaga
path = kagglehub.dataset_download("shubh0799/churn-modelling")
df = pd.read_csv(os.path.join(path, os.listdir(path)[0]))
df.drop(columns = ['RowNumber', 'CustomerId', 'Surname'], inplace=True)
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
numerical_cols = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'EstimatedSalary']

synthetic_data = CHDS_synthesizer(input_df=df,
                                  num_records_to_generate=df.shape[0],
                                  numerical_cols=numerical_cols,
                                  burn_in=2000)
synthetic_data

#Samples: (10000, 11)
#Numerical features: 6
#Categorical features: 5
#Dimension after preprocessing: (10000, 17)

Local Maximal Convex Position Constructing: 100%|██████████| 7500/7500 [00:33<00:00, 224.85it/s]

7500 convex positions constructed

Adjacency Matrix Constructing: 100%|██████████| 7500/7500 [00:38<00:00, 193.34it/s]

Transition Matrix Constructing . . . Completed

MCMC Phase: burn_in: 100%|██████████| 2000/2000 [00:08<00:00, 230.90it/s]
MCMC Phase: synthesis: 100%|██████████| 10000/10000 [00:43<00:00, 227.68it/s]

 -> Burn-in Acceptance Rate  : 73.48%
 -> Synthesis Acceptance Rate : 73.07%

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,679,Germany,Female,50,7,1.328495e+05,1,1,1,106869.915209,0
1,714,Spain,Female,31,6,1.293497e+05,1,0,1,92565.356357,0
2,705,France,Female,32,2,1.420643e+05,2,1,0,48972.033944,0
3,724,Germany,Female,35,5,1.028169e+05,1,1,0,158730.772839,0
4,630,Germany,Female,33,3,1.034831e+05,1,0,0,146635.821241,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,769,Spain,Female,30,3,1.222385e+05,1,1,0,50690.470031,0
9996,681,France,Male,49,7,1.259434e+05,1,1,0,28928.759614,1
9997,669,Germany,Male,32,3,1.517093e+05,1,1,0,61883.572368,0
9998,779,France,Male,36,5,-4.365575e-11,2,1,0,80164.009512,0
9999,724,France,Female,32,4,0.000000e+00,2,1,0,138592.149623,0