In [1]:
from CHDS import CHDS_synthesizer
import pandas as pd
import kagglehub
import os

In [2]:
# Example usaga
path = kagglehub.dataset_download("shubh0799/churn-modelling")
df = pd.read_csv(os.path.join(path, os.listdir(path)[0]))
df.drop(columns = ['RowNumber', 'CustomerId', 'Surname'], inplace=True)
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
numerical_cols = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'EstimatedSalary']
N,d = df.shape
synthetic_data = CHDS_synthesizer(input_df=df,
                                  num_records_to_generate=N,
                                  numerical_cols=numerical_cols,
                                  k_neighbor=d+3,
                                  n_hull=int(3/4*N),
                                  burn_in=2000)
synthetic_data

#Samples: (10000, 11)
#Numerical features: 6
#Categorical features: 5
#Dimension after preprocessing: (10000, 17)

Local Maximal Convex Position Constructing: 100%|██████████| 7500/7500 [00:43<00:00, 171.19it/s]

7500 convex positions constructed

Adjacency Matrix Constructing: 100%|██████████| 7500/7500 [00:43<00:00, 171.79it/s]

Transition Matrix Constructing . . . Completed

MCMC Phase: burn_in: 100%|██████████| 2000/2000 [00:08<00:00, 225.24it/s]
MCMC Phase: synthesis: 100%|██████████| 10000/10000 [00:45<00:00, 219.24it/s]

 -> Burn-in Acceptance Rate  : 75.10%
 -> Synthesis Acceptance Rate : 74.17%

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,635,Germany,Male,32,8,117441.634777,1,1,0,62053.878842,0
1,656,Germany,Male,29,2,109363.913285,2,0,1,129830.452578,0
2,590,Germany,Female,34,7,128121.177084,2,1,1,74116.262727,0
3,543,Spain,Male,31,2,133005.249968,1,1,1,49157.593188,0
4,664,Germany,Male,35,3,145359.608275,1,1,1,46193.188063,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,730,Germany,Female,30,5,117109.203330,1,1,0,129502.164557,0
9996,525,France,Male,31,2,123487.777242,1,1,0,77030.977520,0
9997,647,Spain,Female,37,1,122692.661305,0,1,0,83788.521660,0
9998,755,France,Male,35,1,117088.497144,0,1,1,128379.296871,0
9999,592,Spain,Male,28,7,125003.192394,0,1,1,140849.959190,0